version: "3.1"
services:
    dbt_pineapple_core:
        container_name: dbt_pineapple_core
        image: dbt_pineapple_core:dev
        environment:
            - ENV_NAME=dev
            - DBT_PROJECT=dev-pineapple-pipeline
            - DBT_DEFAULT_DATASET=application
            - DBT_PROFILES_DIR=/app/
