version: "3.1"
services:
    dbt_pineapple_core:
        container_name: dbt_pineapple_core
        image: dbt_pineapple_core:dev
        profiles: ["dbt"]
        ports:
            - "9444:8080"
        volumes:
            - ./:/app:delegated
            # The below volume stores your container's bash history between container runs
            - ./.container_bash_history:/root/.bash_history
            - $HOME/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
        environment:
            - ENV_NAME=dev
            - DBT_PROJECT=dev-pineapple-pipeline
            - DBT_DEFAULT_DATASET=default
            - DBT_PROFILES_DIR=/app/
