# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

ci: # this needs to match the profile: in your dbt_project.yml file
    target: ci
    outputs:
        ci:
            type: bigquery
            method: service-account-json
            project: "{{ env_var('DBT_PROJECT', 'dev-pineapple-pipeline') }}" # Replace this with your project ID
            dataset: "{{ env_var('DBT_DEFAULT_DATASET', 'dbt_ci') }}" # Replace this with dbt_your_name, e.g. dbt_bob
            threads: 4
            timeout_seconds: 600
            location: US
            priority: interactive
            keyfile_json:
              type: "service_account"
              project_id: "dev-pineapple-pipeline"
              private_key_id: "90fcf0ed5e709f7df6b1c8401771c0e56b0f12f2"
              private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDPffG0ZpQSEz73\nWLLzPtfEGual7bXBxCzbCTnTBPLgU2zG5Wtn/Ts5zQaam69BHzSecJTYreNR/brA\n9QzcuaYHfHEBJGv65ylRpSxz5+3xKUSeaEY0WnR+NWj0YIZy59ue02bmgQpx7TiA\n/6MVz9YwX+D0GgLeB3knCGIpdVfuDt0iU8fS96TLW+NtuVwmuqGbMVYpRQ1BTYxj\naEtY3KMsw5PyaS7jphkKmqpoAxzvmKhsIxDfREzmE0uKny7NGsb/UvUk6u5GZCXC\nDAXBpo5IqR7BwmX3Lk23RGQDbHsorjgmhYhnuz9eAQoVLY5rbbkUsOoOLTUMluH9\nPDj3I121AgMBAAECggEADhW50FntP7vcOJymCyKPMYH0+bsE7UoUlGrQKM2rcgRf\nvDGrJJQ5Tr9m7RxX3XcRkpbIV9wX9AMiCAKqdJpKlbQCFMaE6PODp8XrWlPaYFZB\nkPI5n8irIz0baolZ3xdznlix4cBNNfYZMZKI3sxsuPxtMAzK+Ijv1bE5PqC3TxLG\nacM9+8dFTb4WqDpaVZVZZebCTCWb2NrlqK5X1St1tCgPXF70Gn58I3xSC69Pw6iW\nS/dbxGZLaLoCPi2/CI3tB0r8vwQOZFBBoj0eMqwtfGGZ0Y1uBYvq9Rvai2xDypU7\n1TkfPnV0BB9PKu71az4t2dTk33MBAFN3j6832j39QQKBgQDv9a4f68J6L60Gh/IT\ncctRMfUyFZ5sysTev4tDHI+WU2/BU9sK+hHYehTTJ/pwDQzJaloYmPLp5/oa9J/Y\nOy1DhwoKabaCbANrj8CxvQng7nBXPGA3ug6SSZwjKU80gioDv4ON2S1lY+1xCGx+\nhDQYN0enZj/71BwQQfat93vZ9QKBgQDdXKipq+TJakXsHTx0dV3bkUMmXpuQdBL/\n3cgV1GNTvJyv6OYRwp3XDxCiwU0GxVKLlEFIC4EPCMcPvwNA28nGF/DBwnPMFsMS\n0JzfPnctjsE0jv5WSnpKzF8ewWj6PY3kMCuvknD+lcXIBU8tGGfJsSGTxgs0+N3N\nRwuB6LBcwQKBgQDda/zC48/O49NrZWKRYr3ULJ8vGhfYF7tWN7WPtfkhI9jJslE7\nbcmt0ekJd6h2YPRdn0+HxwrPoAl/eh9Nbj20RBWVyjppWrZFOJ78440MC7mKJeI7\nSepMPrRfFa1KrJmMX9pKuA5VssHVPYqvq9pORiROaeG8xNsofVXc7bNRSQKBgBIo\nh61jbGEZVqMHwu3KsuhQAjIjkJ9I5kYW61LfGUbFMhU8BaNvU4NQuQygzrC/fwX0\nI2bFitCw56NjB+FKJkMZs6YxTU5wj4/7jOLDPQN/slmdYT+y3FVGbocXVoUwh3Mw\ngGTmnl5D6vV9egE4/0qMPTTiCglOYON18Hu3msABAoGBAJ8mvsuOza88T1gN2uwK\nBoD/TwyjfmuRpbh9jqIhhRoXxDNoNMBnI6sUCPiavf6n4jkfjKgCYHWJTH8E2oUW\nUn9ximUKVkPnwTWgeLDudwFLGMsqOoDBXbEj9E73R0yRYtca3dhwJlZaYFm2TSH6\nQV0ldA79cbJJRNvHI66xyP+E\n-----END PRIVATE KEY-----\n"
              client_email: "dbt-ci-service-account@dev-pineapple-pipeline.iam.gserviceaccount.com"
              client_id: "101217784114309276515"
              auth_uri: "https://accounts.google.com/o/oauth2/auth"
              token_uri: "https://oauth2.googleapis.com/token"
              auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
              client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/dbt-ci-service-account%40dev-pineapple-pipeline.iam.gserviceaccount.com"
