# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

paper_dbt: # this needs to match the profile: in your dbt_project.yml file
    target: ci
    outputs:
        ci:
            type: bigquery
            method: oauth
            project: "{{ env_var('DBT_PROJECT', 'dev-pineapple-pipeline') }}" # Replace this with your project ID
            dataset: "{{ env_var('DBT_DEFAULT_DATASET', 'dbt_ci) }}" # Replace this with dbt_your_name, e.g. dbt_bob
            threads: 4
            timeout_seconds: 600
            location: us-east4
            priority: interactive
