steps:
    - name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args: ['-c', 'echo DBT_PRIVATE_KEY_ID=$$DBT_PRIVATE_KEY_ID && echo DBT_PRIVATE_KEY=$$DBT_PRIVATE_KEY && echo DBT_METADATA_API_TOKEN=$$DBT_METADATA_API_TOKEN']
      secretEnv: ['DBT_PRIVATE_KEY_ID', 'DBT_PRIVATE_KEY', 'DBT_METADATA_API_TOKEN']

    - name: gcr.io/cloud-builders/docker
      secretEnv: ['DBT_PRIVATE_KEY_ID', 'DBT_PRIVATE_KEY', 'DBT_METADATA_API_TOKEN']
      args: 
          - "build"
          - "-t"
          - "ci_image"
          - "--file=./Dockerfile"
          - .     
      timeout: 1200s
      id: Build Image

    - name: gcr.io/cloud-builders/docker
      entrypoint: 'bash'
      secretEnv: ['DBT_PRIVATE_KEY_ID', 'DBT_PRIVATE_KEY', 'DBT_METADATA_API_TOKEN']
      args: ["-c", "docker run --env DBT_PRIVATE_KEY_ID=$$DBT_PRIVATE_KEY_ID -t ci_image"]

timeout: 1800s
images:
    - "ci_image"
options:
    substitutionOption: ALLOW_LOOSE
substitutions:
    _GCR_HOSTNAME: gcr.io
    _SERVICE_NAME: data-pipeline-ci
    _SERVICE_ACCOUNT: dbt-ci-service-account@dev-pineapple-pipeline.iam.gserviceaccount.com
    _PAPER_BUILD_PROJECT_ID: "dev-pineapple-pipeline"
availableSecrets:
  secretManager:
  - versionName: projects/974000444247/secrets/dbt_private_key_id/versions/1
    env: 'DBT_PRIVATE_KEY_ID'
  - versionName: projects/974000444247/secrets/dbt_private_key/versions/3
    env: 'DBT_PRIVATE_KEY' 
  - versionName: projects/974000444247/secrets/dbt_metadata_api_token/versions/1
    env: 'DBT_METADATA_API_TOKEN'
