steps:
    - name: gcr.io/cloud-builders/docker
      secretEnv: ['DBT_PRIVATE_KEY_ID', 'DBT_PRIVATE_KEY']
      args:
          - "build"
          - "-t"
          - "$_GCR_HOSTNAME/$_PAPER_BUILD_PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
          - "--file=./Dockerfile"
          - .
      timeout: 1200s
      id: Build Image
    - name: gcr.io/cloud-builders/docker
      secretEnv: ['DBT_PRIVATE_KEY_ID', 'DBT_PRIVATE_KEY']
      args:
        - "run" 
        - "-t"
        - "$_GCR_HOSTNAME/$_PAPER_BUILD_PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
timeout: 1800s
images:
    - "$_GCR_HOSTNAME/$_PAPER_BUILD_PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
options:
    substitutionOption: ALLOW_LOOSE
substitutions:
    _GCR_HOSTNAME: gcr.io
    _SERVICE_NAME: data-pipeline-ci
    _SERVICE_ACCOUNT: dbt-ci-service-account@dev-pineapple-pipeline.iam.gserviceaccount.com
    _PAPER_BUILD_PROJECT_ID: "dev-pineapple-pipeline"
availableSecrets:
  secretManager:
  - versionName: projects/974000444247/secrets/dbt_private_key_id/versions/1
    env: 'DBT_PRIVATE_KEY_ID'
  - versionName: projects/974000444247/secrets/dbt_private_key/versions/2
    env: 'DBT_PRIVATE_KEY' 
