steps:
    - name: gcr.io/cloud-builders/docker
      args:
          - "build"
          - "-t"
          - "$_GCR_HOSTNAME/$_PAPER_BUILD_PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
          - "--file=./Dockerfile"
          - .
      timeout: 1200s
      id: Build Image
    - name: gcr.io/cloud-builders/docker
      args:
        - "run" 
        - "-t"
        - "$_GCR_HOSTNAME/$_PAPER_BUILD_PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
timeout: 1800s
images:
    - "$_GCR_HOSTNAME/$_PAPER_BUILD_PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
options:
    substitutionOption: ALLOW_LOOSE
substitutions:
    _GCR_HOSTNAME: gcr.io
    _SERVICE_NAME: data-pipeline-ci
    _SERVICE_ACCOUNT: dbt-ci-service-account@dev-pineapple-pipeline.iam.gserviceaccount.com
    _PAPER_BUILD_PROJECT_ID: "dev-pineapple-pipeline"
tags:
    - gcp-cloud-build-deploy-cloud-run
    - gcp-cloud-build-deploy-cloud-run-managed
    - pubsub-random-event-generator
