steps:
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ "export DBT_PRIVATE_KEY_ID=$(gcloud secrets versions access 1 --secret=dbt_private_key_id)" ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ "export DBT_PRIVATE_KEY=$(gcloud secrets versions access 1 --secret=dbt_private_key)" ]
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: 'bash'
      args: [ "export DBT_METADATA_API_TOKEN=$(gcloud secrets versions access 1 --secret=dbt_metadata_api_token)" ]
    - name: gcr.io/cloud-builders/docker
      secretEnv: ['DBT_PRIVATE_KEY_ID', 'DBT_PRIVATE_KEY', 'DBT_METADATA_API_TOKEN']
      args:
          - "build"
          - "-t"
          - "$_GCR_HOSTNAME/$_PAPER_BUILD_PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
          - "--file=./Dockerfile"
          - .
      timeout: 1200s
      id: Build Image
    - name: gcr.io/cloud-builders/docker
      secretEnv: ['DBT_PRIVATE_KEY_ID', 'DBT_PRIVATE_KEY', 'DBT_METADATA_API_TOKEN']
      args:
        - "run" 
        - "-t"
        - "$_GCR_HOSTNAME/$_PAPER_BUILD_PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
timeout: 1800s
images:
    - "$_GCR_HOSTNAME/$_PAPER_BUILD_PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA"
options:
    substitutionOption: ALLOW_LOOSE
substitutions:
    _GCR_HOSTNAME: gcr.io
    _SERVICE_NAME: data-pipeline-ci
    _SERVICE_ACCOUNT: dbt-ci-service-account@dev-pineapple-pipeline.iam.gserviceaccount.com
    _PAPER_BUILD_PROJECT_ID: "dev-pineapple-pipeline"
availableSecrets:
  secretManager:
  - versionName: projects/974000444247/secrets/dbt_private_key_id/versions/1
    env: 'DBT_PRIVATE_KEY_ID'
  - versionName: projects/974000444247/secrets/dbt_private_key/versions/3
    env: 'DBT_PRIVATE_KEY' 
  - versionName: projects/974000444247/secrets/dbt_metadata_api_token/versions/1
    env: 'DBT_METADATA_API_TOKEN'
